[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seed_contract = "5a8S3GcbPbutDnCLMiwQ1tZLCLyermnKQpiydfs8DMw7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elizabeth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
